# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alexandreroulin/KINU

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alexandreroulin/KINU

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexandreroulin/KINU/CMakeFiles /Users/alexandreroulin/KINU/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexandreroulin/KINU/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named KINU

# Build rule for target.
KINU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KINU
.PHONY : KINU

# fast build rule for target.
KINU/fast:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/build
.PHONY : KINU/fast

Component.o: Component.cpp.o

.PHONY : Component.o

# target to build an object file
Component.cpp.o:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/Component.cpp.o
.PHONY : Component.cpp.o

Component.i: Component.cpp.i

.PHONY : Component.i

# target to preprocess a source file
Component.cpp.i:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/Component.cpp.i
.PHONY : Component.cpp.i

Component.s: Component.cpp.s

.PHONY : Component.s

# target to generate assembly for a file
Component.cpp.s:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/Component.cpp.s
.PHONY : Component.cpp.s

Entity.o: Entity.cpp.o

.PHONY : Entity.o

# target to build an object file
Entity.cpp.o:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/Entity.cpp.o
.PHONY : Entity.cpp.o

Entity.i: Entity.cpp.i

.PHONY : Entity.i

# target to preprocess a source file
Entity.cpp.i:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/Entity.cpp.i
.PHONY : Entity.cpp.i

Entity.s: Entity.cpp.s

.PHONY : Entity.s

# target to generate assembly for a file
Entity.cpp.s:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/Entity.cpp.s
.PHONY : Entity.cpp.s

EventsManager.o: EventsManager.cpp.o

.PHONY : EventsManager.o

# target to build an object file
EventsManager.cpp.o:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/EventsManager.cpp.o
.PHONY : EventsManager.cpp.o

EventsManager.i: EventsManager.cpp.i

.PHONY : EventsManager.i

# target to preprocess a source file
EventsManager.cpp.i:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/EventsManager.cpp.i
.PHONY : EventsManager.cpp.i

EventsManager.s: EventsManager.cpp.s

.PHONY : EventsManager.s

# target to generate assembly for a file
EventsManager.cpp.s:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/EventsManager.cpp.s
.PHONY : EventsManager.cpp.s

SystemsManager.o: SystemsManager.cpp.o

.PHONY : SystemsManager.o

# target to build an object file
SystemsManager.cpp.o:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/SystemsManager.cpp.o
.PHONY : SystemsManager.cpp.o

SystemsManager.i: SystemsManager.cpp.i

.PHONY : SystemsManager.i

# target to preprocess a source file
SystemsManager.cpp.i:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/SystemsManager.cpp.i
.PHONY : SystemsManager.cpp.i

SystemsManager.s: SystemsManager.cpp.s

.PHONY : SystemsManager.s

# target to generate assembly for a file
SystemsManager.cpp.s:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/SystemsManager.cpp.s
.PHONY : SystemsManager.cpp.s

World.o: World.cpp.o

.PHONY : World.o

# target to build an object file
World.cpp.o:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/World.cpp.o
.PHONY : World.cpp.o

World.i: World.cpp.i

.PHONY : World.i

# target to preprocess a source file
World.cpp.i:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/World.cpp.i
.PHONY : World.cpp.i

World.s: World.cpp.s

.PHONY : World.s

# target to generate assembly for a file
World.cpp.s:
	$(MAKE) -f CMakeFiles/KINU.dir/build.make CMakeFiles/KINU.dir/World.cpp.s
.PHONY : World.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... KINU"
	@echo "... Component.o"
	@echo "... Component.i"
	@echo "... Component.s"
	@echo "... Entity.o"
	@echo "... Entity.i"
	@echo "... Entity.s"
	@echo "... EventsManager.o"
	@echo "... EventsManager.i"
	@echo "... EventsManager.s"
	@echo "... SystemsManager.o"
	@echo "... SystemsManager.i"
	@echo "... SystemsManager.s"
	@echo "... World.o"
	@echo "... World.i"
	@echo "... World.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

